---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.6"
    hooks:
      - id: ruff
        files: "core\/|notebooks\/"
      - id: ruff-format
        files: "core\/|notebooks\/"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-toml
        files: "pyproject.toml"

ci:
  autofix_prs: false
  autoupdate_schedule: quarterly
