###########################################################
# ruff on both ./code/* and ./core/ during infra prep phase
###########################################################

files: "code\/|core\/"
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.5"
    hooks:
      - id: ruff
      - id: ruff-format
