name: simplification
channels:
  - conda-forge
dependencies:
  - python=3.11
  - bokeh
  - clustergram
  - contextily
  - dask
  - dask-geopandas
  - esda>=2.5.1
  - geopandas>=0.13.0
  - graphblas-algorithms
  - h3-py=3.7.7
  - ipykernel
  - jupyterlab
  - matplotlib>=3.9
  - momepy>=0.9.0
  - osmnx>=1.9.1
  - pointpats>=2.3.0
  - pip
  - pyarrow
  - pyogrio
  - rasterio
  - scikit-learn>=1.2
  - tobler>=0.11.3
  - tqdm>=4.63.0
  - watermark
  # standard formatting
  - pre-commit
  - ruff
  # tqdm warning - TqdmWarning: IProgress not found
  - jupyter
  - ipywidgets
  - pip:
    # not available via conda-forge:
    - opencv-python
    - cityseer
    - parenx
    # from bleeding edge functionality
    - git+https://github.com/uscuni/neatnet.git
