 name: Continuous Integration

 on:
   push:
     branches: [main]
   pull_request:
     branches:
       - "*"
   schedule:
     - cron: '59 23 * * *'
   workflow_dispatch:
    inputs:
      version:
        description: Manual CI Run
        default: test
        required: false

 jobs:
   tests:
     name: ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
     timeout-minutes: 30
     strategy:
       matrix:
         os: [ubuntu-latest, macos-latest, macos-14, windows-latest]
       fail-fast: false

     defaults:
       run:
         shell: bash -l {0}

     steps:
       - name: checkout repo
         uses: actions/checkout@v4
         with:
           fetch-depth: 0 # Fetch all history for all branches and tags.

       - name: Setup Pixi
         uses: prefix-dev/setup-pixi@v0.8.1
         with:
            cache: true
            environments: "tests"

       - name: spatial versions
         run: 'pixi run -e tests python -c "import geopandas; geopandas.show_versions();"'

       - name: run tests
         run:
           pixi run -e tests \
           pytest . \
           --verbose \
           -r a \
           --numprocesses logical \
           --color yes \
           --cov core \
           --cov-append \
           --cov-report term-missing \
           --cov-report xml . \

       - name: codecov
         uses: codecov/codecov-action@v4
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
